# Generated by Django 5.2 on 2025-12-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mensagem',
            new_name='comentario',
        ),
        migrations.RemoveField(
            model_name='post',
            name='titulo',
        ),
        migrations.AddField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
