# Generated by Django 5.2 on 2025-12-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_mensagem_post_comentario_remove_post_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comentario',
            field=models.TextField(blank=True),
        ),
    ]
